/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MarcasRouteImport } from './routes/marcas'
import { Route as LocalizacaoRouteImport } from './routes/localizacao'
import { Route as EmpresaRouteImport } from './routes/empresa'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'

const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MarcasRoute = MarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalizacaoRoute = LocalizacaoRouteImport.update({
  id: '/localizacao',
  path: '/localizacao',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresaRoute = EmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/localizacao': typeof LocalizacaoRoute
  '/marcas': typeof MarcasRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/localizacao': typeof LocalizacaoRoute
  '/marcas': typeof MarcasRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/empresa': typeof EmpresaRoute
  '/localizacao': typeof LocalizacaoRoute
  '/marcas': typeof MarcasRoute
  '/pedidos': typeof PedidosRoute
  '/produtos': typeof ProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/empresa'
    | '/localizacao'
    | '/marcas'
    | '/pedidos'
    | '/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/empresa'
    | '/localizacao'
    | '/marcas'
    | '/pedidos'
    | '/produtos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/empresa'
    | '/localizacao'
    | '/marcas'
    | '/pedidos'
    | '/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EmpresaRoute: typeof EmpresaRoute
  LocalizacaoRoute: typeof LocalizacaoRoute
  MarcasRoute: typeof MarcasRoute
  PedidosRoute: typeof PedidosRoute
  ProdutosRoute: typeof ProdutosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marcas': {
      id: '/marcas'
      path: '/marcas'
      fullPath: '/marcas'
      preLoaderRoute: typeof MarcasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/localizacao': {
      id: '/localizacao'
      path: '/localizacao'
      fullPath: '/localizacao'
      preLoaderRoute: typeof LocalizacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresa': {
      id: '/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof EmpresaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EmpresaRoute: EmpresaRoute,
  LocalizacaoRoute: LocalizacaoRoute,
  MarcasRoute: MarcasRoute,
  PedidosRoute: PedidosRoute,
  ProdutosRoute: ProdutosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
